"""make url unique per user

Revision ID: 02c7acb0305a
Revises: c97beae8c0fb
Create Date: 2026-09-03 17:22:52.722206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c7acb0305a'
down_revision: Union[str, Sequence[str], None] = 'c97beae8c0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sources_url_key'), 'sources', type_='unique')
    op.create_unique_constraint('uq_source_url_owner', 'sources', ['url', 'owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_source_url_owner', 'sources', type_='unique')
    op.create_unique_constraint(op.f('sources_url_key'), 'sources', ['url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
