"""add unique constraintto source url

Revision ID: 17c83fd2261e
Revises: c041833270c0
Create Date: 2026-08-24 18:32:51.656694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c83fd2261e'
down_revision: Union[str, Sequence[str], None] = 'c041833270c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sources', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='unique')
    # ### end Alembic commands ###
