"""add created_at to sources

Revision ID: 836767c6a8ef
Revises: dc52233c784e
Create Date: 2026-08-20 20:52:52.134569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836767c6a8ef'
down_revision: Union[str, Sequence[str], None] = 'dc52233c784e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'created_at')
    # ### end Alembic commands ###
