"""add owner_id to sources

Revision ID: c97beae8c0fb
Revises: 06bf93605f57
Create Date: 2026-09-03 16:43:13.710803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97beae8c0fb'
down_revision: Union[str, Sequence[str], None] = '06bf93605f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_sources_owner_id'), 'sources', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'sources', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_index(op.f('ix_sources_owner_id'), table_name='sources')
    op.drop_column('sources', 'owner_id')
    # ### end Alembic commands ###
